
strategy:
    _target_: flwr.server.strategy.QFedAvg
    fraction_fit: 0.5
    min_fit_clients: ${num_clients_per_round_fit}
    fraction_evaluate: 0.01
    min_evaluate_clients: ${num_clients_per_round_eval}
    min_available_clients: ${num_clients}
    on_fit_config_fn:
      _target_: server.get_on_fit_config
      config: ${config_fit}
    initial_parameters:  
      _target_: model.model_to_parameters  
  # Başlangıç parametreleri, verilen modelin parametrelerine dayalı olarak tanımlanır.
      model: ${model} 
    